language: rust
rust: 
 - stable

install:
  - cargo install cargo-binutils rustfilt

branches:
  only: 
    - main

jobs:
  include:
    - stage: check
      if: type = pull_request
      script: make check
    - stage: build
      if: type = pull_request
      script: make qemu
    - stage: deploy
      if: type = push
      script: make check
      script: mke qemu
