[package]
name = "kernel"
version = "0.1.0"
authors = ["twrdyyy varsill"]
edition = "2018"

[features]
default = []
bsp_rpi3 = []

[profile.release]
lto = true

[dependencies]

[target.'cfg(target_arch = "aarch64")'.dependencies]
cortex-a = { version = "5.x.x" }